version: '3.7'
services:
    resume_backend:
        container_name: resume_backend
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: docker_env_php80
        ports:
            - '2525:2525'
            - '80:80'
        working_dir: /var/www/resume_backend
        volumes:
            - './:/var/www/resume_backend'
            - './docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf'
            - './docker/entry_point.sh:/usr/local/bin/entry_point.sh'
        restart: unless-stopped
        entrypoint:
            - /usr/local/bin/entry_point.sh
        command: 'bash -c "apachectl -D FOREGROUND"'
        networks:
            - app
    resume_backend_node:
        container_name: resume_backend_node
        image: docker_env_php80
        ports:
            - '3001:3001'
            - '5173:5173'
        working_dir: /var/www/resume_backend
        volumes:
            - './:/var/www/resume_backend'
            - './docker/entry_node.sh:/usr/local/bin/entry_node.sh'
        tty: true
        restart: unless-stopped
        entrypoint:
            - /usr/local/bin/entry_node.sh
        networks:
            - app
    db:
        image: mysql:8.1
        container_name: mysql_db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_DATABASE: resume_app
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306:3306
        networks:
        - app
        volumes:
            - mysql_db_volume:/var/lib/mysql
            - ./docker/backups/mysql:/var/backups/mysql

volumes:
    mysql_db_volume:

networks:
    app:
        name: local
        external: true

