name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

   
    # - uses: isbang/compose-action@v1.4.1
      # with:
      #   compose-file: "docker-compose.yml"
      #   down-flags: "--volumes"
    # - name: Set up Docker Compose
      # run:  |
      #   docker-compose down
      #   docker-compose -f docker-compose.yml up -d

    # - name: Set AWS PEM Key
    #   run: echo "$AWS_PEM_KEY" > aws.pem
    #   env:
    #     AWS_PEM_KEY: ${{ secrets.EC2_SECRET }}

    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USERNAME}}
        key: ${{ secrets.EC2_SECRET }}
        script: |
            cd /var/www/resume_backend
            git pull origin master
            sudo docker-compose down
            sudo docker-compose up -d
