name: Docker Image CICD
on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

   
    # - uses: isbang/compose-action@v1.4.1
      # with:
      #   compose-file: "docker-compose.yml"
      #   down-flags: "--volumes"
    # - name: Set up Docker Compose
      # run:  |
      #   docker-compose down
      #   docker-compose -f docker-compose.yml up -d

    # - name: Set AWS PEM Key
    #   run: echo "$AWS_PEM_KEY" > aws.pem
    #   env:
    #     AWS_PEM_KEY: ${{ secrets.EC2_SECRET }}

    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USERNAME}}
        key: ${{ secrets.EC2_SECRET }}
        script_stop: true
        script: |
            cd /var/www/resume_backend
            git checkout .
            git pull origin test
            # cp .env.production .env
            # cp docker-compose.test.yml docker-compose.yml
            docker-compose build
            docker-compose down
            docker-compose up -d
            
    # - name: pull from repository
    #   run: |  
    #       cd /var/www/resume_backend
    #       git pull origin test


    # - name: deploy
    #   if: ${{ github.event.pull_request.merged == true && !failure() }}
    #   run: | 
    #     cp .env.production .env
    #     cp docker-compose.test.yml docker-compose.yml
    #     docker-compose build
    #     docker-compose down
    #     docker-compose up -d
            
             